version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "currency"
      POSTGRES_USER: "Illia"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
  app:
    depends_on:
      - postgres
    build: .
    container_name: app
    environment:
      DB_SERVER: "postgres"
    ports:
      - "8080:8080"
    links:
      - postgres